### ISSUE TITLE
Ability to right-click within text fields

### ISSUE THREAD

**Issue by JPW0080** [devilismyfriend/StableTuner#11]
Can the Ability to right-click within text fields to for instance, paste text be implemented?
Currently, lots of CTRL+V's have been in order.

**Comment by devilismyfriend** [comment]
Added in the latest commit

**Comment by JPW0080** [comment]
Thanks, perhaps the Caption Buddy can get the same treatment?

**Comment by devilismyfriend** [comment]
Done
