### ISSUE TITLE
Triton can't be installed/found?

### ISSUE THREAD

**Issue by r6spy** [devilismyfriend/StableTuner#110]
after the last update, somehow some things got to work after alot of reinstallations and stuff
but i can't seem to get triton to work

Error caught was: No module named 'triton'

when i try to install manually it i get.

pip install triton==1.1.1
did not work

also tried
(ST) E:\StableTuner>pip install --upgrade --force-reinstall triton==1.1.1
ERROR: Could not find a version that satisfies the requirement triton==1.1.1 (from versions: none)
ERROR: No matching distribution found for triton==1.1.1

**Comment by devilismyfriend** [comment]
you can ignore that message, triton isn't currently available on windows.
