### ISSUE TITLE
Blank screen when using SD 2.1 768

### ISSUE THREAD

**Issue by MV799** [devilismyfriend/StableTuner#28]
This could be an user error.
When I used SD 2.1 768 as base with correct 768 training set it created the sample images all fine in the folders but at the end NONE saved set would produce any image in the playground, nor any checkpoint converted would do in A1111. The image would be all blank. (black)

This is curious (especially because the sample images were all fine so it did worked at some point during training)

What could be the issue?

(no problem with 2.1 512 base)

BTW, I absolutely love the interface and how easy it is to run!

**Comment by MV799** [comment]
I tried second time, the same result - the samples are good - and looking really fine, the checkpoint is blank in either playground or A1111

**Comment by MV799** [comment]
I think the issue is f16

**Comment by devilismyfriend** [comment]
This was fixed yesterday, please try to git pull the latest and let me know

**Comment by MV799** [comment]
Yup, fixed in the last pull. Excellent!
