### ISSUE TITLE
Question. ColossalAI

### ISSUE THREAD

**Issue by dill-shower** [devilismyfriend/StableTuner#48]
Does StableTuner use the optimization methods that ColossalAI uses?
Ability to train with batch size=8 with only 9gb vram
Much faster learning

[Stable Diffusion with Colossal-AI](https://github.com/hpcaitech/ColossalAI/tree/main/examples/images/diffusion) provides 6.5x faster training and pretraining cost saving, the hardware cost of fine-tuning can be almost 7X cheaper (from RTX3090/4090 24GB to RTX3050/2070 8GB)

**Comment by devilismyfriend** [comment]
It doesn't and since colossal is built around lighting I'm not sure it
will.
