### ISSUE TITLE
Crash when train_text_encoder is false and conditional_dropout > 0

### ISSUE THREAD

**Issue by RossM** [devilismyfriend/StableTuner#59]
When `args.train_text_encoder` is false, `CachedLatentsDataset.cache.text_encoder_cache` contains preencoded token embeddings rather than token IDs. However, `CachedLatentsDataset.empty_tokens` is still filled with token_ids. When `args.conditional_dropout` is nonzero, this results in batches selected for conditional dropout getting token IDs where embeddings are expected, and the training crashes due to mismatching tensor sizes.

I looked into fixing this but gave up for the moment so I'm reporting it as a bug.

**Comment by devilismyfriend** [comment]
fixed
