### ISSUE TITLE
Requires Hugging Face Token, nowhere to set

### ISSUE THREAD

**Issue by ctorx** [devilismyfriend/StableTuner#6]
I didn't see anywhere in the setting for where to set this.

<img width="851" alt="image" src="https://user-images.githubusercontent.com/343783/206058465-73ff3653-9f20-4ab9-9ae5-eb8da42de2e9.png">

**Comment by devilismyfriend** [comment]
pushed a fix, should work now without a token, might be added in the future if there's a need for it again.

**Comment by ctorx** [comment]
I will check it out, thank you.
