### ISSUE TITLE
Change wrecked ability to train subjects

### ISSUE THREAD

**Issue by Enyakk** [devilismyfriend/StableTuner#69]
One of the very recent changes after commit

cbe04acdf120aa4b5b1506e3120c421fb92df49a

wrecked the ability to train subjects in Dreambooth mode. I can A/B the repositories and there's a stark difference in likeness and quality. Possibly one of the CLIP changes?

**Comment by Claxiz** [comment]
I am having this issue too, except I couldnt even start training. Switching to an older version 3 commits ago solved my problems.

**Comment by geocine** [comment]
I am having this issue too. I tried several times.

**Comment by devilismyfriend** [comment]
I reverted from the latest big change, please check again

**Comment by devilismyfriend** [comment]
also make sure to post your configs

**Comment by Jordach** [comment]
Was regular image captions used alongside the class caption/prompt/token setting? This may hint at further issues.

**Comment by blackmagic24** [comment]
> I reverted from the latest big change, please check again

It works again for me.

**Comment by geocine** [comment]
@devilismyfriend  works again for me. However the Model Playground now is broken

```sh
Traceback (most recent call last):
  File "C:\Users\moo\miniconda3\envs\ST\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\moo\miniconda3\envs\ST\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 531, in _clicked
    self._command()
  File "E:\AIML\StableTuner\scripts\configuration_gui.py", line 1907, in <lambda>
    self.play_toolbox_label = ctk.CTkLabel(self.playground_frame_subframe, text="Toolbox")
  File "E:\AIML\StableTuner\scripts\configuration_gui.py", line 2271, in play_generate_image
    with torch.autocast("cuda"), torch.inference_mode():
AttributeError: play_current_image
```
