### ISSUE TITLE
Feature request: Export to Cloud option / Script

### ISSUE THREAD

**Issue by mediocreatmybest** [devilismyfriend/StableTuner#73]
Hi! 

I love the export to cloud option, it would be great if it also included an export to shell script toggle option. 
All of the commands are already there just wrapped within a notebook. 

Would make it a great way to edit / modify model for training within the existing interface. Export to Cloud --> Upload to Linux box and "press play on tape", it might be a useful way to have a Linux option without having to worry about a GUI yet etc. 

Obviously, it needs a script to create and setup the environment first etc.

**Comment by devilismyfriend** [comment]
you can right-click the export button to copy a shell command, just copy and paste to the notebook to run

**Comment by mediocreatmybest** [comment]
> you can right-click the export button to copy a shell command, just copy and paste to the notebook to run

Don't think I tried right clicking. I'll have a look at this tonight. Thanks :)
