### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'  durring installation

### ISSUE THREAD

**Issue by r6spy** [devilismyfriend/StableTuner#76]
hi guys i'm trying to install the stabletuner like you explained but i get this when i run the bat file
also my miniconda is not in C:\ its in d:\
i've taken in to considuration that i need to make custom-conda-path.txt in the folder,but this is what i get when i run it

Environment name is set as ST as per environment.yaml
anaconda3/miniconda3 detected in "e:\Users\SPYBG\miniconda3"
Found Anaconda
The filename, directory name, or volume label syntax is incorrect.
'conda' is not recognized as an internal or external command,
operable program or batch file.
The filename, directory name, or volume label syntax is incorrect.
Traceback (most recent call last):
  File "E:\StableTuner\scripts\windows_install.py", line 9, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Press any key to continue . . .

**Comment by devilismyfriend** [comment]
requests is a default python library, check your environment.
