### ISSUE TITLE
Support training with different aspect ratios of than squares

### ISSUE THREAD

**Issue by ProGamerGov** [devilismyfriend/StableTuner#82]
Currently it seems like you can only specific the size of the height and width dimensions together for a square shape. I would like to be able to independently specify different height and width values, for certain kinds of training data that for example uses a 1:2 ratio (768x1536) and requires that the entire image be visible to the model during each training step.

**Comment by ProGamerGov** [comment]
Actually, I think aspect ratio bucketing may already do this? https://github.com/NovelAI/novelai-aspect-ratio-bucketing

**Comment by Jordach** [comment]
StableTuner already supports aspect ratio bucketing.
